/**
 * Flashcards System - Vocabulary flashcards with SRS
 */

class FlashcardSystem {
  constructor(db) {
    this.db = db;
    this.storeName = 'flashcards';
    this.engine = new SRSEngine(); // Reuse SRS algorithm
  }

  async init() {
    if (!this.db) throw new Error('Database not initialized');
    return this;
  }

  _normalizeTerm(termRaw) {
    if (typeof termRaw !== 'string') return '';
    return termRaw
      .toLowerCase()
      .trim()
      .replace(/\s+/g, ' ')
      .replace(/^[^a-z0-9]+/i, '')
      .replace(/[^a-z0-9]+$/i, '');
  }

  _inferTermType(normalizedTerm) {
    return normalizedTerm.includes(' ') ? 'phrase' : 'word';
  }

  async _getCardsByTerm(normalizedTerm) {
    const tx = this.db.transaction(this.storeName, 'readonly');
    const store = tx.objectStore(this.storeName);

    if (store.indexNames.contains('termNormalized')) {
      const index = store.index('termNormalized');
      return new Promise((resolve, reject) => {
        const request = index.getAll(normalizedTerm);
        request.onsuccess = () => resolve(request.result || []);
        request.onerror = () => reject(request.error);
      });
    }

    const all = await idbGetAll(store);
    return all.filter(card => card.termNormalized === normalizedTerm);
  }

  async _findAutoBayesCard(normalizedTerm) {
    if (!normalizedTerm) return null;
    const candidates = await this._getCardsByTerm(normalizedTerm);
    return candidates.find(card => card.sourceType === 'auto_bayes') || null;
  }

  async createFlashcard(word, translation, context = '', deck = 'FUVEST', metadata = {}) {
    if (!this.db) return null;

    const srs = this.engine.createCard(word);
    const normalizedTerm = metadata.termNormalized || this._normalizeTerm(word);
    const termType = metadata.termType || this._inferTermType(normalizedTerm);
    const autoGenerated = !!metadata.autoGenerated;
    const sourceType = autoGenerated ? 'auto_bayes' : (metadata.sourceType || 'manual');
    const vocabId = metadata.vocabId || null;
    if (autoGenerated && !vocabId) {
      console.warn('[FlashcardSystem] Auto-generated card requires vocabId.');
      return null;
    }

    if (sourceType === 'auto_bayes') {
      const existingAutoCard = await this._findAutoBayesCard(normalizedTerm);
      if (existingAutoCard) return existingAutoCard;
    }

    const nowIso = new Date().toISOString();

    const card = {
      id: metadata.id || `fc_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      word,
      translation: translation || '',
      context,
      deck,
      createdAt: nowIso,
      termNormalized: normalizedTerm,
      termType,
      sourceType,
      sourceRefs: metadata.sourceRefs || {},
      difficultySnapshot: metadata.difficultySnapshot || null,
      autoGenerated,
      vocabId,
      repetitions: srs.repetitions,
      easeFactor: srs.easeFactor,
      interval: srs.interval,
      nextReview: srs.nextReview,
      reviewCount: srs.reviewCount,
      history: srs.history || []
    };

    const tx = this.db.transaction(this.storeName, 'readwrite');
    const store = tx.objectStore(this.storeName);
    const existing = await idbGet(store, card.id);
    if (existing) return existing;

    await idbAdd(store, card);
    return card;
  }

  async getDueCards(deck = null, limit = 20) {
    if (!this.db) return [];
    
    const tx = this.db.transaction(this.storeName, 'readonly');
    const store = tx.objectStore(this.storeName);
    const cards = await idbGetAll(store);
    
    let dueCards = cards.filter(c => this.engine.isDue(c));
    if (deck) {
      dueCards = dueCards.filter(c => c.deck === deck);
    }
    
    return dueCards.slice(0, limit);
  }

  async reviewCard(cardId, quality) {
    if (!this.db) return null;

    const tx = this.db.transaction(this.storeName, 'readwrite');
    const store = tx.objectStore(this.storeName);

    const card = await idbGet(store, cardId);
    if (!card) return null;

    const updated = this.engine.review(card, quality);

    if (!updated.termNormalized) {
      updated.termNormalized = this._normalizeTerm(updated.word || '');
    }
    if (!updated.termType) {
      updated.termType = this._inferTermType(updated.termNormalized || '');
    }

    await idbPut(store, updated);

    if (window.wordIntelligence) {
      const context = {
        textId: updated.sourceRefs?.textId || null,
        examId: updated.sourceRefs?.examId || null,
        topic: updated.sourceRefs?.topic || null,
        institution: updated.sourceRefs?.institution || null
      };
      // Non-blocking: review flow should never fail because of analytics enrichment.
      window.wordIntelligence.recordFlashcardReview(updated.word, quality, context).catch(() => null);
    }

    // Log flashcard review
    if (window.behaviorLogger) {
      window.behaviorLogger.log('click', 'flashcard', 'review_card', {
        cardId, quality, word: card.word
      });
    }

    // Award XP for flashcard review
    if (window.xpSystem) {
      window.xpSystem.awardXP(3, 'flashcard_review');
    }

    // Update daily challenge
    if (window.dailyChallenge) {
      window.dailyChallenge.recordProgress('srs_reviews', 1);
    }

    return updated;
  }

  async getAllDecks() {
    if (!this.db) return [];
    
    const tx = this.db.transaction(this.storeName, 'readonly');
    const store = tx.objectStore(this.storeName);
    const cards = await idbGetAll(store);
    
    const decks = [...new Set(cards.map(c => c.deck))];
    return decks.map(name => ({
      name,
      totalCards: cards.filter(c => c.deck === name).length,
      dueCards: cards.filter(c => c.deck === name && this.engine.isDue(c)).length
    }));
  }

  async getAllCards(deck = null) {
    if (!this.db) return [];
    const tx = this.db.transaction(this.storeName, 'readonly');
    const store = tx.objectStore(this.storeName);
    let cards = await idbGetAll(store);
    if (deck) cards = cards.filter(c => c.deck === deck);
    return cards.sort((a, b) => a.word.localeCompare(b.word));
  }

  async getStats() {
    if (!this.db) return { total: 0, due: 0, new: 0 };
    
    const tx = this.db.transaction(this.storeName, 'readonly');
    const store = tx.objectStore(this.storeName);
    const cards = await idbGetAll(store);
    
    return {
      total: cards.length,
      due: cards.filter(c => this.engine.isDue(c)).length,
      new: cards.filter(c => c.repetitions === 0).length,
      mature: cards.filter(c => c.repetitions >= 3).length
    };
  }
}

class FlashcardUI {
  constructor(flashcardSystem) {
    this.system = flashcardSystem;
    this.currentCard = null;
    this.isFlipped = false;
  }

  async renderDeckSelector(containerId) {
    const container = document.getElementById(containerId);
    if (!container) return;

    const decks = await this.system.getAllDecks();
    const stats = await this.system.getStats();

    container.innerHTML = `
      <div class="flashcard-decks">
        <h3>Seus Decks</h3>
        <div class="decks-grid">
          ${decks.map(deck => `
            <div class="deck-card" data-deck="${deck.name}">
              <span class="deck-name">${deck.name}</span>
              <span class="deck-stats">${deck.dueCards} para revisar / ${deck.totalCards} total</span>
            </div>
          `).join('')}
        </div>
        <div class="flashcard-stats">
          <div class="fc-stat">Total: ${stats.total}</div>
          <div class="fc-stat">Para revisar: ${stats.due}</div>
          <div class="fc-stat">Novos: ${stats.new}</div>
        </div>
        <button id="btn-start-review" class="btn-primary" ${stats.due === 0 ? 'disabled' : ''}>
          Iniciar Revisão (${stats.due})
        </button>
      </div>
    `;

    container.querySelector('#btn-start-review')?.addEventListener('click', () => {
      this.startReview();
    });
  }

  async startReview() {
    const cards = await this.system.getDueCards(null, 50);
    if (cards.length === 0) {
      if (window.showToast) showToast('Nenhum card para revisar!', 'info');
      return;
    }
    this.cards = cards;
    this.currentIndex = 0;
    this.showCard();
  }

  showCard() {
    this.currentCard = this.cards[this.currentIndex];
    if (!this.currentCard) return;

    let modal = document.querySelector('.flashcard-modal');
    if (!modal) {
      modal = document.createElement('div');
      modal.className = 'flashcard-modal';
      document.body.appendChild(modal);
      modal.addEventListener('click', (e) => {
        if (e.target === modal) modal.remove();
      });
    }

    const isFirst = this.currentIndex === 0;
    const isLast = this.currentIndex === this.cards.length - 1;

    modal.innerHTML = `
      <div class="flashcard-container">
        <div class="flashcard-top-bar">
          <button class="flashcard-manage-btn" id="fc-manage" aria-label="Gerenciar flashcards" title="Gerenciar flashcards">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/>
              <circle cx="12" cy="12" r="3"/>
            </svg>
          </button>
          <button class="flashcard-close" aria-label="Fechar">&times;</button>
        </div>
        <div class="flashcard-nav">
          <button class="flashcard-nav-btn" id="fc-prev" ${isFirst ? 'disabled' : ''} aria-label="Anterior">&larr;</button>
          <span class="flashcard-nav-counter">Card ${this.currentIndex + 1} de ${this.cards.length}</span>
          <button class="flashcard-nav-btn" id="fc-next" ${isLast ? 'disabled' : ''} aria-label="Proximo">&rarr;</button>
        </div>
        <div class="flashcard" onclick="this.classList.toggle('flipped')">
          <div class="flashcard-front">
            <span class="word">${this.currentCard.word}</span>
            <span class="context">${this.currentCard.context || ''}</span>
            <div class="flip-hint">
              <div class="flip-hint-icon">
                <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/>
                  <path d="M21 3v5h-5"/>
                  <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/>
                  <path d="M3 21v-5h5"/>
                </svg>
              </div>
              <span>Toque para revelar</span>
            </div>
          </div>
          <div class="flashcard-back">
            <span class="translation">${this.currentCard.translation}</span>
          </div>
        </div>
        <div class="flashcard-controls">
          <button class="rating-btn again" data-quality="0">De novo</button>
          <button class="rating-btn hard" data-quality="3">Dificil</button>
          <button class="rating-btn good" data-quality="4">Bom</button>
          <button class="rating-btn easy" data-quality="5">Facil</button>
        </div>
      </div>
    `;

    modal.querySelector('.flashcard-close').onclick = () => modal.remove();

    modal.querySelector('#fc-manage')?.addEventListener('click', () => {
      modal.remove();
      window.location.hash = '#/flashcard-list';
    });

    modal.querySelector('#fc-prev')?.addEventListener('click', () => {
      if (this.currentIndex > 0) { this.currentIndex--; this.showCard(); }
    });

    modal.querySelector('#fc-next')?.addEventListener('click', () => {
      if (this.currentIndex < this.cards.length - 1) { this.currentIndex++; this.showCard(); }
    });

    modal.querySelectorAll('.rating-btn').forEach(btn => {
      btn.addEventListener('click', async (e) => {
        const quality = parseInt(e.target.dataset.quality);
        await this.system.reviewCard(this.currentCard.id, quality);
        this.cards.splice(this.currentIndex, 1);
        if (this.cards.length === 0) {
          modal.remove();
          if (window.showToast) showToast('Revisao completa! Parabens!', 'success');
          return;
        }
        if (this.currentIndex >= this.cards.length) this.currentIndex = this.cards.length - 1;
        this.showCard();
      });
    });
  }
}

class FlashcardListUI {
  constructor(flashcardSystem) {
    this.system = flashcardSystem;
    this.currentDeck = null;
  }

  async render(containerId) {
    const container = document.getElementById(containerId);
    if (!container) return;

    const [cards, decks, stats] = await Promise.all([
      this.system.getAllCards(this.currentDeck),
      this.system.getAllDecks(),
      this.system.getStats()
    ]);

    const correctTotal = cards.reduce((sum, c) => sum + (c.repetitions || 0), 0);
    const reviewTotal = cards.reduce((sum, c) => sum + (c.reviewCount || 0), 0);
    const incorrectTotal = reviewTotal - correctTotal;
    const accuracy = reviewTotal > 0 ? Math.round((correctTotal / reviewTotal) * 100) : 0;

    container.innerHTML = `
      <div class="fc-list">
        <div class="fc-list-summary">
          <div class="fc-summary-item">
            <span class="fc-summary-value">${stats.total}</span>
            <span class="fc-summary-label">Total</span>
          </div>
          <div class="fc-summary-item">
            <span class="fc-summary-value">${stats.due}</span>
            <span class="fc-summary-label">Para revisar</span>
          </div>
          <div class="fc-summary-item">
            <span class="fc-summary-value">${stats.mature}</span>
            <span class="fc-summary-label">Dominados</span>
          </div>
          <div class="fc-summary-item">
            <span class="fc-summary-value">${accuracy}%</span>
            <span class="fc-summary-label">Acerto</span>
          </div>
        </div>

        <div class="fc-list-filters">
          <button class="fc-filter-btn ${!this.currentDeck ? 'active' : ''}" data-deck="">Todos</button>
          ${decks.map(d => `<button class="fc-filter-btn ${this.currentDeck === d.name ? 'active' : ''}" data-deck="${d.name}">${d.name} (${d.totalCards})</button>`).join('')}
        </div>

        <div class="fc-list-actions">
          ${stats.due > 0
            ? `<button class="fc-start-review-btn" id="fc-list-start-review"><i data-lucide="play"></i> Iniciar Revisao (${stats.due})</button>`
            : stats.total > 0
              ? `<button class="fc-start-review-btn fc-start-review-btn--all" id="fc-list-study-all"><i data-lucide="book-open"></i> Estudar Todos (${stats.total})</button>`
              : ''}
          <button class="fc-toggle-translations" id="fc-toggle-translations">
            <i data-lucide="eye"></i> Mostrar traducoes
          </button>
        </div>

        <div class="fc-card-list" data-translations="hidden">
          ${cards.length === 0 ? '<p class="empty-state">Nenhum flashcard encontrado.</p>' : cards.map(c => this._renderCard(c)).join('')}
        </div>
      </div>
    `;

    if (window.lucide) window.lucide.createIcons();
    this._attachListeners(container, containerId);
  }

  _renderCard(card) {
    const reviews = card.reviewCount || 0;
    const correct = card.repetitions || 0;
    const incorrect = reviews - correct;
    const isDue = this.system.engine.isDue(card);
    const isNew = reviews === 0;
    const isMature = correct >= 3;

    let statusClass = 'fc-status-new';
    let statusText = 'Novo';
    if (isMature) { statusClass = 'fc-status-mature'; statusText = 'Dominado'; }
    else if (reviews > 0) { statusClass = 'fc-status-learning'; statusText = 'Aprendendo'; }
    if (isDue && !isNew) { statusClass = 'fc-status-due'; statusText = 'Revisar'; }

    const nextDate = card.nextReview ? new Date(card.nextReview) : null;
    const nextText = nextDate ? nextDate.toLocaleDateString('pt-BR', { day: '2-digit', month: '2-digit' }) : '--';

    return `
      <div class="fc-card-item">
        <div class="fc-card-word">
          <strong>${card.word}</strong>
          <span class="fc-card-translation">${card.translation}</span>
        </div>
        <div class="fc-card-stats">
          <span class="fc-card-score fc-correct" title="Acertos">${correct}</span>
          <span class="fc-card-score fc-incorrect" title="Erros">${incorrect < 0 ? 0 : incorrect}</span>
          <span class="fc-card-next" title="Proxima revisao">${nextText}</span>
          <span class="fc-card-status ${statusClass}">${statusText}</span>
        </div>
      </div>
    `;
  }

  _attachListeners(container, containerId) {
    container.querySelectorAll('.fc-filter-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        this.currentDeck = btn.dataset.deck || null;
        this.render(containerId);
      });
    });

    container.querySelector('#fc-list-start-review')?.addEventListener('click', () => {
      const ui = new FlashcardUI(this.system);
      ui.startReview();
    });

    container.querySelector('#fc-list-study-all')?.addEventListener('click', async () => {
      const ui = new FlashcardUI(this.system);
      const allCards = await this.system.getAllCards(this.currentDeck);
      if (allCards.length === 0) {
        if (window.showToast) showToast('Nenhum flashcard encontrado!', 'info');
        return;
      }
      ui.cards = allCards;
      ui.currentIndex = 0;
      ui.showCard();
    });

    const toggleBtn = container.querySelector('#fc-toggle-translations');
    const cardList = container.querySelector('.fc-card-list');
    if (toggleBtn && cardList) {
      toggleBtn.addEventListener('click', () => {
        const hidden = cardList.dataset.translations === 'hidden';
        cardList.dataset.translations = hidden ? 'visible' : 'hidden';
        toggleBtn.innerHTML = hidden
          ? '<i data-lucide="eye-off"></i> Ocultar traducoes'
          : '<i data-lucide="eye"></i> Mostrar traducoes';
        if (window.lucide) window.lucide.createIcons();
      });
    }
  }
}

window.FlashcardSystem = FlashcardSystem;
window.FlashcardUI = FlashcardUI;
window.FlashcardListUI = FlashcardListUI;
