import { expect, test } from '@playwright/test';

const BASE = process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:8080';

async function openApp(page: any, viewport: { width: number; height: number }) {
  await page.setViewportSize(viewport);
  await page.goto(`${BASE}/#/`, { waitUntil: 'networkidle' });
  await page.waitForFunction(() => (window as any).appReady === true, { timeout: 15000 });
}

test.describe('Batch 1 Validation (F1/F2/F3)', () => {
  test('F1/F2: Bayesian persistence + auto-card idempotency', async ({ page }) => {
    await openApp(page, { width: 1366, height: 768 });

    const result = await page.evaluate(async () => {
      const db = (window as any).state?.db;
      const wi = (window as any).wordIntelligence;
      if (!db || !wi) return { ok: false, reason: 'runtime_not_ready' };

      const seed = `batch1_${Date.now()}`;
      const context = {
        textId: 'text_1',
        examId: '2026-1ed',
        topic: 'technology_ai',
        institution: 'FUVEST',
        translation: 'tradução de teste',
        textSnippet: 'snippet',
      };

      await wi.recordTranslationSignal(seed, { ...context, questionId: `${seed}_q1` });
      await wi.recordTranslationSignal(seed, { ...context, questionId: `${seed}_q2` });
      await wi.recordFlashcardReview(seed, 1, { ...context, questionId: `${seed}_q3` });
      await wi.recordFlashcardReview(seed, 0, { ...context, questionId: `${seed}_q4` });

      const vocabId = `voc_${seed}`;
      const vocabTx = db.transaction('vocabulary', 'readonly');
      const vocab = await (window as any).idbGet(vocabTx.objectStore('vocabulary'), vocabId);

      const cardsTx = db.transaction('flashcards', 'readonly');
      const cards = await (window as any).idbGetAll(cardsTx.objectStore('flashcards'));
      const autoCards = cards.filter((c: any) => c.termNormalized === seed && c.sourceType === 'auto_bayes');

      // Re-trigger creation path, must remain idempotent.
      await wi.recordTranslationSignal(seed, { ...context, questionId: `${seed}_q5` });
      const cardsTx2 = db.transaction('flashcards', 'readonly');
      const cards2 = await (window as any).idbGetAll(cardsTx2.objectStore('flashcards'));
      const autoCardsAfter = cards2.filter((c: any) => c.termNormalized === seed && c.sourceType === 'auto_bayes');

      return {
        ok: true,
        vocabExists: !!vocab,
        difficultyScore: vocab?.difficultyScore,
        reliability: vocab?.reliability,
        observations: vocab?.observations,
        translateClicks: vocab?.signals?.translateClicks || 0,
        linkedCardId: vocab?.flashcardLink?.cardId || null,
        autoCardsCountBefore: autoCards.length,
        autoCardsCountAfter: autoCardsAfter.length,
        autoCard: autoCardsAfter[0]
          ? {
              sourceType: autoCardsAfter[0].sourceType,
              vocabId: autoCardsAfter[0].vocabId,
              autoGenerated: autoCardsAfter[0].autoGenerated,
              snapshotScore: autoCardsAfter[0].difficultySnapshot?.score ?? null,
            }
          : null,
      };
    });

    expect(result.ok).toBe(true);
    expect(result.vocabExists).toBe(true);
    expect(result.observations).toBeGreaterThanOrEqual(3);
    expect(result.translateClicks).toBeGreaterThanOrEqual(2);
    expect(result.difficultyScore).toBeGreaterThanOrEqual(70);
    expect(result.autoCardsCountBefore).toBe(1);
    expect(result.autoCardsCountAfter).toBe(1);
    expect(result.linkedCardId).toBeTruthy();
    expect(result.autoCard?.sourceType).toBe('auto_bayes');
    expect(result.autoCard?.vocabId).toBeTruthy();
    expect(result.autoCard?.autoGenerated).toBe(true);
  });

  test('F2: help-features translation pipeline records signal', async ({ page }) => {
    await openApp(page, { width: 1200, height: 800 });

    const result = await page.evaluate(async () => {
      const db = (window as any).state?.db;
      const help = (window as any).helpFeatures;
      const wi = (window as any).wordIntelligence;
      if (!db || !help || !wi) return { ok: false, reason: 'runtime_not_ready' };

      const seed = `helpbatch${Date.now()}`;

      // Isolate from provider/network instability.
      help.callLLM = async () => 'traducao simulada';
      help.setContext(
        { id: 'text_1', exam_id: '2026-1ed', topic: 'technology_ai', source: 'FUVEST', text: 'sample text' },
        { id: `${seed}q1` }
      );

      await help.translateText(seed, null);
      await new Promise(resolve => setTimeout(resolve, 350));

      const tx = db.transaction('vocabulary', 'readonly');
      const record = await (window as any).idbGet(tx.objectStore('vocabulary'), `voc_${seed}`);
      return {
        ok: true,
        exists: !!record,
        translateClicks: record?.signals?.translateClicks ?? 0,
        observations: record?.observations ?? 0,
      };
    });

    expect(result.ok).toBe(true);
    expect(result.exists).toBe(true);
    expect(result.translateClicks).toBeGreaterThanOrEqual(1);
    expect(result.observations).toBeGreaterThan(0);
  });

  test('F3: UI rename, weak terms surfaces and metadata in desktop/tablet/mobile', async ({ page }) => {
    const viewports = [
      { name: 'desktop', width: 1366, height: 768 },
      { name: 'tablet', width: 834, height: 1112 },
      { name: 'mobile', width: 390, height: 844 },
    ];

    for (const viewport of viewports) {
      await openApp(page, { width: viewport.width, height: viewport.height });

      // Seed one difficult term in this isolated browser context so UI checks are deterministic.
      const seeded = await page.evaluate(async () => {
        const wi = (window as any).wordIntelligence;
        if (!wi) return { ok: false };
        const seed = `f3seed_${Date.now()}`;
        const context = {
          textId: 'text_1',
          examId: '2026-1ed',
          topic: 'technology_ai',
          institution: 'FUVEST',
          translation: 'tradução',
          textSnippet: 'snippet',
        };
        await wi.recordTranslationSignal(seed, { ...context, questionId: `${seed}_q1` });
        await wi.recordTranslationSignal(seed, { ...context, questionId: `${seed}_q2` });
        await wi.recordFlashcardReview(seed, 1, { ...context, questionId: `${seed}_q3` });
        await wi.recordFlashcardReview(seed, 0, { ...context, questionId: `${seed}_q4` });
        const top = await wi.getTopDifficultTerms(5);
        if (typeof (window as any).updateDashboard === 'function') {
          await (window as any).updateDashboard();
        }
        return { ok: true, topCount: top.length };
      });

      expect(seeded.ok).toBe(true);
      expect(seeded.topCount).toBeGreaterThan(0);

      // Force dashboard refresh cycle after seeding.
      await page.goto(`${BASE}/#/analytics`, { waitUntil: 'networkidle' });
      await page.goto(`${BASE}/#/`, { waitUntil: 'networkidle' });

      const dashboardText = await page.locator('body').innerText();
      expect(dashboardText).not.toMatch(/passagem|passagens/i);
      await expect
        .poll(async () => page.locator('#weakness-list .weakness-item').count(), { timeout: 10000 })
        .toBeGreaterThan(0);

      await page.goto(`${BASE}/#/analytics`, { waitUntil: 'networkidle' });
      await expect(page.locator('#stats-view')).toBeVisible({ timeout: 10000 });
      await expect(page.locator('text=Vocabulário Mais Difícil')).toBeVisible({ timeout: 10000 });
      await expect(page.locator('.weak-term-item').first()).toBeVisible({ timeout: 10000 });

      const metadataCheck = await page.evaluate(async () => {
        const db = (window as any).state?.db;
        if (!db) return { ok: false, reason: 'no_db' };
        const tx = db.transaction('question_bank', 'readonly');
        const all = await (window as any).idbGetAll(tx.objectStore('question_bank'));
        const missing = all.filter((entry: any) => !entry.text_metadata);
        const invalidLexical = all.filter((entry: any) => {
          const lexical = entry.text_metadata?.lexical;
          if (!lexical) return true;
          if ((entry.text || '').trim().length > 0 && lexical.estimatedReadingTime < 1) return true;
          return false;
        });
        return { ok: true, total: all.length, missing: missing.length, invalidLexical: invalidLexical.length };
      });

      expect(metadataCheck.ok).toBe(true);
      expect(metadataCheck.total).toBeGreaterThan(0);
      expect(metadataCheck.missing).toBe(0);
      expect(metadataCheck.invalidLexical).toBe(0);
    }
  });

  test('Project console should stay error-free during core navigation', async ({ page }) => {
    const errors: string[] = [];
    page.on('console', (msg: any) => {
      if (msg.type() === 'error') {
        errors.push(msg.text());
      }
    });

    await openApp(page, { width: 1200, height: 800 });
    await page.goto(`${BASE}/#/study`, { waitUntil: 'networkidle' });
    await page.goto(`${BASE}/#/analytics`, { waitUntil: 'networkidle' });
    await page.goto(`${BASE}/#/`, { waitUntil: 'networkidle' });

    expect(errors, `Console errors found: ${errors.join(' | ')}`).toEqual([]);
  });
});
